# Generated by Django 6.0.3 on 2026-03-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_content_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='body',
            field=models.TextField(help_text='Contenu de cet onglet'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(help_text="Nom de l'onglet (ex: Histoire)", max_length=100),
        ),
    ]
